version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookflow
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    ports:
      - '8080:8080'
    depends_on:
      - db
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bookflow?schema=public
      PORT: 3001
  # LEGACY_BASE_URL should point to external BookStack when used, e.g. http://host.docker.internal:8081
    ports:
      - '3001:3001'
    depends_on:
      - db
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  db_data:
